// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDher7KtwYRY3hocKb_aN9wKelSB0_YfeA',
    appId: '1:308029957568:web:01fe487c334b8bbcb39425',
    messagingSenderId: '308029957568',
    projectId: 'flutter-login-demo-bd643',
    authDomain: 'flutter-login-demo-bd643.firebaseapp.com',
    storageBucket: 'flutter-login-demo-bd643.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCA16uZUDWWdYc4oFejAmIWYtZKG6d1TrY',
    appId: '1:308029957568:android:6fe8ed02cb9e0349b39425',
    messagingSenderId: '308029957568',
    projectId: 'flutter-login-demo-bd643',
    storageBucket: 'flutter-login-demo-bd643.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD33QkoMUBrnAmPVP2fWK8wpu3FdsIx0Zs',
    appId: '1:308029957568:ios:a39ab9fb32497f29b39425',
    messagingSenderId: '308029957568',
    projectId: 'flutter-login-demo-bd643',
    storageBucket: 'flutter-login-demo-bd643.firebasestorage.app',
    iosBundleId: 'com.example.flutterLoginDemo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD33QkoMUBrnAmPVP2fWK8wpu3FdsIx0Zs',
    appId: '1:308029957568:ios:a39ab9fb32497f29b39425',
    messagingSenderId: '308029957568',
    projectId: 'flutter-login-demo-bd643',
    storageBucket: 'flutter-login-demo-bd643.firebasestorage.app',
    iosBundleId: 'com.example.flutterLoginDemo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDher7KtwYRY3hocKb_aN9wKelSB0_YfeA',
    appId: '1:308029957568:web:8c067dcad5961698b39425',
    messagingSenderId: '308029957568',
    projectId: 'flutter-login-demo-bd643',
    authDomain: 'flutter-login-demo-bd643.firebaseapp.com',
    storageBucket: 'flutter-login-demo-bd643.firebasestorage.app',
  );
}
