import 'package:flutter/material.dart';
import 'package:firebase_core/firebase_core.dart';
import 'firebase_options.dart'; // generated by flutterfire configure
import 'theme.dart';
import 'analytics_service.dart';
import 'home_screen.dart';
import 'pdp_screen.dart';
import 'login_screen.dart';
import 'checkout_screen.dart';
import 'confirmation_screen.dart';
import 'product_model.dart';

void main() async {
  WidgetsFlutterBinding.ensureInitialized();
  await Firebase.initializeApp(options: DefaultFirebaseOptions.currentPlatform);
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Holafly Store',
      debugShowCheckedModeBanner: false,
      theme: HolaflyTheme.theme,
      navigatorObservers: [AnalyticsService.observer],
      initialRoute: '/',
      onGenerateRoute: (settings) {
        switch (settings.name) {
          case '/':
            return MaterialPageRoute(builder: (_) => const HomeScreen());
          case '/pdp':
            final product = settings.arguments as Product;
            return MaterialPageRoute(
                builder: (_) => PdpScreen(product: product));
          case '/login':
            final args = settings.arguments as Map<String, dynamic>?;
            return MaterialPageRoute(
                builder: (_) => LoginScreen(nextRoute: args?['nextRoute']));
          case '/checkout':
            final product = settings.arguments as Product;
            return MaterialPageRoute(
                builder: (_) => CheckoutScreen(product: product));
          case '/confirmation':
            final args = settings.arguments as Map<String, dynamic>;
            return MaterialPageRoute(
                builder: (_) => ConfirmationScreen(
                      product: args['product'] as Product,
                      transactionId: args['transactionId'] as String,
                    ));
          default:
            return MaterialPageRoute(builder: (_) => const HomeScreen());
        }
      },
    );
  }
}
